# Project information
site_name: "Homepage"
site_description: ""
site_author: "derrors"
site_url: "https://derrors.github.io/derrors-project/"


# Repository
repo_name: "Derrors"
repo_url: "https://github.com/Derrors"


# Copyright
copyright: "Copyright &copy; 2019 - 2020 Qinghe Li"


# Configuration
theme:
  name: "material"

  palette:
    primary: "deep purple"
    accent: "deep purple"

  font:
    text: "Ubuntu"
    code: "Ubuntu Mono"

  #logo:
    #icon: "cloud"

  favicon: "assets/images/favicon.ico"

  language: "zh"

  feature:
    tabs: "true"


# Customization
extra:
  search:
    language: "zh, en"
    tokenizer: '[\s\-\.]+'

  social:
    - type: "github"
      link: "https://github.com/Derrors"

  manifest: "manifest.webmanifest"


# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji: 
      emoji_generator: !!python/name:pymdownx.emoji.to_png
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg
      #emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_awesome
      #emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

extra_javascript:
  - 'js/extra.js'
  - 'js/baidu-tongji.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'


# Google Analytics
google_analytics:
  - "UA-156919721-1"
  - "auto"


# Tags
nav: 
  - 主页: index.md

  - 仓库:
    - 1. Fact Extraction and Verification:
      - (1) 任务介绍: repositories/fever.md
      - (2) FEVER-NSMN: repositories/nsmn.md
      - (3) FEVER-FFFFFF: repositories/ffffff.md
    - 2. Review Reading Comprehension: repositories/rrc.md
    - 3. Reviews & Product & QA: repositories/rpqa.md
    - 4. Others: repositories/others.md

  - 笔记: notes/notes.md
  
  - 文档&教程: documents/doc.md
